export interface FollowUser {
  id: string;
  name: string;
  username: string;
  avatar: string;
  bio: string;
  isFollowing: boolean;
  isFollower: boolean;
  mutualFollowers?: number;
}

export const mockFollowers: FollowUser[] = [
  {
    id: '2',
    name: 'Nguyễn Văn A',
    username: '@nguyenvana',
    avatar: 'https://i.pravatar.cc/150?img=1',
    bio: 'Developer | Tech Enthusiast',
    isFollowing: true,
    isFollower: true,
    mutualFollowers: 45,
  },
  {
    id: '3',
    name: 'Trần Thị B',
    username: '@tranthib',
    avatar: 'https://i.pravatar.cc/150?img=2',
    bio: 'Designer | Creative Mind',
    isFollowing: false,
    isFollower: true,
    mutualFollowers: 12,
  },
  {
    id: '4',
    name: 'Lê Văn C',
    username: '@levanc',
    avatar: 'https://i.pravatar.cc/150?img=3',
    bio: 'Photographer | Travel Lover',
    isFollowing: true,
    isFollower: true,
    mutualFollowers: 23,
  },
  {
    id: '5',
    name: 'Phạm Thị D',
    username: '@phamthid',
    avatar: 'https://i.pravatar.cc/150?img=4',
    bio: 'Content Creator | Influencer',
    isFollowing: false,
    isFollower: true,
    mutualFollowers: 8,
  },
  {
    id: '6',
    name: 'Hoàng Văn E',
    username: '@hoangvane',
    avatar: 'https://i.pravatar.cc/150?img=5',
    bio: 'Entrepreneur | Business Owner',
    isFollowing: true,
    isFollower: true,
    mutualFollowers: 67,
  },
  {
    id: '7',
    name: 'Đặng Thị F',
    username: '@dangthif',
    avatar: 'https://i.pravatar.cc/150?img=6',
    bio: 'Marketing Specialist',
    isFollowing: false,
    isFollower: true,
    mutualFollowers: 5,
  },
  {
    id: '8',
    name: 'Vũ Văn G',
    username: '@vuvang',
    avatar: 'https://i.pravatar.cc/150?img=7',
    bio: 'Software Engineer',
    isFollowing: true,
    isFollower: true,
    mutualFollowers: 34,
  },
  {
    id: '9',
    name: 'Bùi Thị H',
    username: '@buithih',
    avatar: 'https://i.pravatar.cc/150?img=8',
    bio: 'Fashion Blogger',
    isFollowing: false,
    isFollower: true,
    mutualFollowers: 19,
  },
];

export const mockFollowing: FollowUser[] = [
  {
    id: '2',
    name: 'Nguyễn Văn A',
    username: '@nguyenvana',
    avatar: 'https://i.pravatar.cc/150?img=1',
    bio: 'Developer | Tech Enthusiast',
    isFollowing: true,
    isFollower: true,
    mutualFollowers: 45,
  },
  {
    id: '3',
    name: 'Trần Thị B',
    username: '@tranthib',
    avatar: 'https://i.pravatar.cc/150?img=2',
    bio: 'Designer | Creative Mind',
    isFollowing: true,
    isFollower: false,
    mutualFollowers: 12,
  },
  {
    id: '4',
    name: 'Lê Văn C',
    username: '@levanc',
    avatar: 'https://i.pravatar.cc/150?img=3',
    bio: 'Photographer | Travel Lover',
    isFollowing: true,
    isFollower: true,
    mutualFollowers: 23,
  },
  {
    id: '10',
    name: 'Đinh Văn I',
    username: '@dinhvani',
    avatar: 'https://i.pravatar.cc/150?img=9',
    bio: 'Music Producer',
    isFollowing: true,
    isFollower: false,
    mutualFollowers: 15,
  },
  {
    id: '11',
    name: 'Mai Thị J',
    username: '@maithij',
    avatar: 'https://i.pravatar.cc/150?img=10',
    bio: 'Yoga Instructor',
    isFollowing: true,
    isFollower: false,
    mutualFollowers: 7,
  },
  {
    id: '5',
    name: 'Phạm Thị D',
    username: '@phamthid',
    avatar: 'https://i.pravatar.cc/150?img=4',
    bio: 'Content Creator | Influencer',
    isFollowing: true,
    isFollower: false,
    mutualFollowers: 8,
  },
  {
    id: '6',
    name: 'Hoàng Văn E',
    username: '@hoangvane',
    avatar: 'https://i.pravatar.cc/150?img=5',
    bio: 'Entrepreneur | Business Owner',
    isFollowing: true,
    isFollower: true,
    mutualFollowers: 67,
  },
  {
    id: '12',
    name: 'Ngô Văn K',
    username: '@ngovank',
    avatar: 'https://i.pravatar.cc/150?img=11',
    bio: 'Chef | Food Blogger',
    isFollowing: true,
    isFollower: false,
    mutualFollowers: 29,
  },
  {
    id: '7',
    name: 'Vũ Văn G',
    username: '@vuvang',
    avatar: 'https://i.pravatar.cc/150?img=7',
    bio: 'Software Engineer',
    isFollowing: true,
    isFollower: true,
    mutualFollowers: 34,
  },
  {
    id: '13',
    name: 'Cao Thị L',
    username: '@caothil',
    avatar: 'https://i.pravatar.cc/150?img=12',
    bio: 'Fitness Coach',
    isFollowing: true,
    isFollower: false,
    mutualFollowers: 11,
  },
];